### ISSUE TITLE
can't play music. Only loading 

### ISSUE THREAD

**Issue by utsavpatel51** [sir-kain/vscode-mediaplayer#17]

**Comment by sir-kain** [comment]
Hello!
- Which operating system are you using?
- Can you try this following command on your terminal `mpv https://s.mp3-send.com/stream/3uWBZB:Skv1rB` ?
The sound should start (It's just to know if you have correctly installed the **mpv** dependence on your computer)

**Comment by utsavpatel51** [comment]
currently I'm using Windows 10
mpv https://s.mp3-send.com/stream/3uWBZB:Skv1rB
It's working on terminal
![image](https://user-images.githubusercontent.com/26016485/73003512-cfdb6800-3e2b-11ea-8c92-ebde30644cf6.png)

**Comment by sir-kain** [comment]
Could you:
- tell me the type of research you did? Podcast or Youtube?
- send a screenshot of the error form the developer tools of Vscode (Help -> Toggle Developer Tools)?

**Comment by utsavpatel51** [comment]
It's from YouTube
![image](https://user-images.githubusercontent.com/26016485/73374390-1a535d80-42e0-11ea-9dbb-8a216e8d6084.png)
I played from Favs category and that's song from youtube and after 2 min it's still loading 
![image](https://user-images.githubusercontent.com/26016485/73374505-51297380-42e0-11ea-844a-ba9a5d019cf7.png)

and mpv is working fine from cmd
![image](https://user-images.githubusercontent.com/26016485/73374943-0f4cfd00-42e1-11ea-91d2-50037cc0a43c.png)

**Comment by sir-kain** [comment]
I tested on my side and i had the same behavior as you (it's only loading)
But i fixed it by running this `pip install --upgrade youtube-dl` on my cmd.
Can you try to do same and test again?

It's sure that there are lot of improvements to be done on the extension but for this case I don't really think that it comes from the extension but rather from the mpv dependence.

Please let me know if it's still not working :)

**Comment by utsavpatel51** [comment]
It's working now!!
Thanks

**Comment by vahmelk99** [comment]
I have the same issue and local, global files wont play they are only loading. And when I click to next button or in Loading.. I have this message `command '' not found`

**Comment by sir-kain** [comment]
> I have the same issue and local, global files wont play they are only loading. And when I click to next button or in Loading.. I have this message `command '' not found`

Hello @vahmelk99 did you check if your **mpv** cli is up to date.

This error comes up a lot of times but it is often related to the mpv cli or youtube-dl installed on your computer
Please try to follow  [these steps](https://github.com/sir-kain/vscode-mediaplayer/issues/17#issuecomment-580532700) and tell up

**Comment by vahmelk99** [comment]
![image](https://user-images.githubusercontent.com/30202111/102511225-f50b4180-40a1-11eb-8fc7-e5c80c6b0939.png)

**Comment by sir-kain** [comment]
Hello,

can someone confirm if the new release (v1.6.2) really fixed the issue?
