### ISSUE TITLE
Youtube: o is not a function

### ISSUE THREAD

**Issue by Shadowsith** [sir-kain/vscode-mediaplayer#31]
Hello,

thanks a lot for this great extension.
I have the problem that as soon as I try to search something from Youtube the error message "o is not a function" appears in the UI and no results are displayed. 

Postcast search and local works fine.

mpv and youtube-dl (version 2020.09.20) are installed.
Operating system: Manjaro Linux

**Comment by sir-kain** [comment]
Hello,

glad you appreciate!!
Yea. it's because I have reached the Youtube API v3 quota that was granted to me.
I don't know how to get an API key for unlimited access for free.

Any suggestion are welcomed.

**Comment by Shadowsith** [comment]
Is there a way to make it possible for the users to add their own Youtube API key as a config setting for this extension?

**Comment by sir-kain** [comment]
> Is there a way to make it possible for the users to add their own Youtube API key as a config setting for this extension?

🆒  Yeah this is a good idea and i think we can go this way.

**Comment by irvana** [comment]
i wish will hear a good news after this

**Comment by SP-XD** [comment]
hii why use youtube api key when youtube-dl provides direct play functionality using "ytsearchX:" (x is for the number of results)

**Comment by SP-XD** [comment]
> Hello,
> 
> glad you appreciate!!
> Yea. it's because I have reached the Youtube API v3 quota that was granted to me.
> I don't know how to get an API key for unlimited access for free.
> 
> Any suggestion are welcomed.

I went and change the API key to mine in extension.ts in vscode directory, yet still 'O is not a function appearing'.

**Comment by vahmelk99** [comment]
I have this issue too "o is not a function"

**Comment by sir-kain** [comment]
Hello,

can someone confirm if the new release (v1.6.2) really fixed the issue?

**Comment by SP-XD** [comment]
> Hello,
> 
> can someone confirm if the new release (v1.6.2) really fixed the issue?

Its working!!!!!!! hurrayyyyyyyyyyyyyyyyyy!!!!1

**Comment by sir-kain** [comment]
> > Hello,
> 
> > 
> 
> > can someone confirm if the new release (v1.6.2) really fixed the issue?
> 
> 
> 
> Its working!!!!!!! hurrayyyyyyyyyyyyyyyyyy!!!!1

Thank you
