### ISSUE TITLE
No Result Matched

### ISSUE THREAD

**Issue by AkDevilHunter** [sir-kain/vscode-mediaplayer#48]
When I Search for a Music In YouTube Or Podcast It Says No Results Matched, but when i check same thing by going to YouTube It Shows Result, Kindly Resolve the issue

**Comment by sir-kain** [comment]
Hello.

Just did the test and I don't have this problem.

![image](https://user-images.githubusercontent.com/8977909/129705144-57a9e097-d306-4649-9a9e-68a161523a4c.png)

Can you check again on your side and tell me if the problem persists?

**Comment by AkDevilHunter** [comment]
Hmm Its Awkard, Just Restarted My PC uninstalled and installed again and it worked, btw thanks for your fast response
